= Catégoriser ses tests avec JUnit
Etienne BESSON
2014-01-01
:jbake-type: post
:jbake-tags: java test junit
:jbake-status: unpublished
:source-highlighter: prettify
:id: categoriser_ses_tests_junit

Cette article est inspiré du travail de http://linsolas.free.fr/wordpress/index.php/2011/02/categoriser-ses-tests-junit-avec-maven/

= Problématique


Le framework JUnit propose l'annotation @Category pour catégoriser ses tests. Cette annotation peut-être utilisée sur une classe ou sur une méthode.
On peux ainsi catégoriser facilement ses tests unitaires, intégration.

Todo parler des tests sur le métier et les niveaux haut médium bas

Pour lancer une suite de tests en utilisant les catégories, JUnit fournit les outils suivant 

* Un runner : Categories pour lancer des tests avec des catégories
* Des annotations pour inclure ou exclure des catégories : IncludeCategory et ExcludeCategory
* Une annotation pour définir les suites de tests : SuiteClasses

Ce qui donne le code suivant pour une suite de tests :
[source,java]
----
@RunWith(Categories.class)
@IncludeCategory(value={HighLevelTest.class,MediumLevelTest.class)
@SuiteClasses( { BuisnessDomainA.class, BuisnessDomainB })
public class MaTestSuite {
 
}
----

L'utilisation du code précédent pose les problèmes suivant :

    Il faut maintenir la liste des classes de tests dans l'annotation SuiteClasses
    Quand que plusieurs catégories sont utilisées dans l'annotation IncludeCategory, le framework fait un "OU" logique entre les catégories. On ne peux pas lancer des suites de tests du type : les HighLevelTest sur BuisnessDomainA.

= Solution

Voici la solution retenue pour résoudre les problèmes précédents est la suivante :

* Générer dynamiquement la suite de tests à partir d'un package à scanner
* Créer une nouvelle annotation pour inclure des catégories avec la possibilité de définir un opérateur logique (ET, OU) entre les catégories

Ces outils sont disponibles dans à l'url suivante :

* Une nouvelle annotation IncludeCategory qui permet de prendre en compte les catégories et l'opérateur logique entre les catégories
* Une nouvelle annotation TestPackageToScann qui permet de définir le package à scanner pour créer dynamiquement la suite de tests
* Un nouveau runner CustomCategories qui permet l’utilisation des annotations IncludeCategory et TestPackageToScann 

= Mise en œuvre

Pour la mise en œuvre nous prendrons l'exemple suivant : je souhaite pourvoir lancer les tests du type BuisnessDomainA sur le BuisnessDomainA

Voici les différentes étapes de mise en oeuvre :

* Création des annotations nécessaires
* Mise en place des annotations
* Création de la suite de tests

Création des annotations nécessaires

Nous allons créer l'annotation métier BuisnessDomainA. Elle nous permettra de marquer toutes les classes de tests qui sont relatives au métier BuisnessDomainA.
[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
public @interface BuisnessDomainA{
}
----

Mise en place des annotations
	

Il ne faut pas oublier de marquer chaque classes de tests relatives à BuisnessDomainA avec la nouvelle annotation
Création de la suite de tests
[source,java]
----
@RunWith(Categories.class)
@IncludeCategory(categories = { BuisnessDomainA.class, HighLevelTest.class }, operator = IncludeCategory.AND)
public class BuisnessDomainAHighLevelTestSuite {
}
----

Intégration avec Maven
Todo exemple de code avec surefire et profile 
